SELECT Id,
       Name,
       UserName,
       NormalizedUserName,
       Email,
       NormalizedEmail,
       EmailConfirmed,
       PasswordHash,
       SecurityStamp,
       ConcurrencyStamp,
       PhoneNumber,
       PhoneNumberConfirmed,
       TwoFactorEnabled,
       LockoutEnd,
       LockoutEnabled,
       AccessFailedCount
FROM   AspNetUsers;